version: '3.8'

services:
  database:
    image: mysql
    container_name: planding
    environment:
      - MYSQL_DATABASE=planding
      - MYSQL_ROOT_PASSWORD=1234
      - TZ= Asia/Seoul
    ports:
      - '3307:3306'


  backend:
    image: rlatkddns1234/planding:tagname
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://planding:3306/planding?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - database